### ISSUE TITLE
[Bug] Unable to upload file larger than 1mb

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/infrastructure#19]
**Describe the bug**

Unable to upload files over certain limit under ghost nginx

**To Reproduce**

1. Visit any blog article under https://blog.podkrepi.bg/ghost/
1. Upload file larger than 1.5mb
1. See error 

```
XHR: 413 Request Entity Too Large via nginx

UI: The image you uploaded was larger than the maximum file size your server allows.
```

**Expected behavior**
Upload the image

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

https://ghost.org/docs/faq/image-upload-issues/

Same as https://stackoverflow.com/a/63379058/668245

Please add `nginx.ingress.kubernetes.io/proxy-body-size` annotation to your ingress configuration file.

**Comment by imilchev** [comment]
Fixed it. I currently set it to 20.
