### ISSUE TITLE
[Feature] Add uploading companion

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/infrastructure#22]
**Is your feature request related to a problem? Please describe.**
In order to upload files to S3 bucket or to source files from Google Drive we need to have Uppy server companion in place

**Describe the solution you'd like**
Prepare and deploy Uppy Companion based on:

- https://uppy.io/docs/companion/#Running-in-Kubernetes
- https://github.com/transloadit/uppy/blob/main/packages/@uppy/companion/KUBERNETES.md
- https://hub.docker.com/r/transloadit/companion

**Describe alternatives you've considered**
Host the companion inside our API layer - this will be sufficient but will require extra effort to be integrated. Standalone server will have restricted access.

**Comment by imilchev** [comment]
Do we really need something so complicated for doing simple file uploads? This requires Redis + an extra service that you need to call from the front-end. Which functionality from Uppy do we actually need? If we are uploading just PDFs then I guess this is not needed at all... Is there something else?

**Comment by kachar** [comment]
I think we need the base functionality for photo manipulation and photo/document upload to S3 storage.
Nothing fancy, only the minimal working set

The photo upload can be seen and tested at https://dev.podkrepi.bg/campaigns/create

**Comment by igoychev** [comment]
Looking at the code the next step is to make uppy work with the S3 plugin as per here: https://uppy.io/docs/aws-s3/

**Comment by igoychev** [comment]
Done by [imilchev](https://github.com/imilchev) in the backend, no changes were needed in infra repo.

**Comment by kachar** [comment]
For the record Uppy integration is not used directly but we have done a manual S3 uploading mechanism
