### ISSUE TITLE
[Feature] Deploy the custom theme for Keycloak

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/infrastructure#23]
## **Is your feature request related to a problem? Please describe.**
We need to add a custom Podkrepi-bg Theme for Keycloak to ensure unified user experience

## **Describe the solution you'd like**
Please install the new Podkrepi Keycloak Theme from here: https://github.com/podkrepi-bg/infrastructure/tree/main/keycloak/theme_podkrepi

The helm chart needs to be edited to download the theme as per the instructions here:
https://issueexplorer.com/issue/bitnami/bitnami-docker-keycloak/20

To enable the theme, go to Admin/Realm/Themes tab and select the theme-podkrepi from the dropdowns. Set internationalization to ON to enable Bulgarian localized messages.

## **Additional context**
The custom theme was created following the Keycloak docs: https://www.keycloak.org/docs/latest/server_development/#creating-a-theme

## Testing performed
The theme was tested by using local Keycloak instance installed with docker-compose like this:

1. Get the docker-compose.yaml
```shell
curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-keycloak/master/docker-compose.yml
```
2. Add the Theme volume mount as per: https://github.com/bitnami/bitnami-docker-keycloak#adding-custom-themes
`volumes:
      - "./theme-podkrepi:/opt/bitnami/keycloak/themes/theme-podkrepi"`
3. Start the container:
```shell
docker-compose up
```

**Comment by imilchev** [comment]
Fixed in 9a198d45f613faccffde8c39bafa6943bdab3e38
