### ISSUE TITLE
[Feature] Translate login screen

### ISSUE THREAD

**Issue by imilchev** [podkrepi-bg/infrastructure#24]
**Describe the solution you'd like**
The translations should be updated such that the entire pages are available in Bulgarian. Files to be updated:
https://github.com/podkrepi-bg/infrastructure/blob/main/keycloak/theme_podkrepi/login/messages/messages_bg.properties
https://github.com/podkrepi-bg/infrastructure/blob/main/keycloak/theme_podkrepi/email/messages/messages_bg.properties
https://github.com/podkrepi-bg/infrastructure/blob/main/keycloak/theme_podkrepi/account/messages/messages_bg.properties

**Additional context**
The placeholders which require translations can be found here:
https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/messages/messages_en.properties 
https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/email/messages/messages_en.properties
https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/account/messages/messages_en.properties

**Comment by igoychev** [comment]
Login/Registrations/Forgotten pass translations added by [GeorgyGenchev](https://github.com/GeorgyGenchev) with this pull request https://github.com/podkrepi-bg/infrastructure/pull/27
TODO: emails and account related translations

**Comment by imilchev** [comment]
@igoychev is this still relevant?

**Comment by igoychev** [comment]
> @igoychev is this still relevant?

not relevant anymore - safe to close
