### ISSUE TITLE
Install Ceph for distributed file storage

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/infrastructure#3]
**Describe the solution you'd like**
The platform needs a distributed file storage to keep user and campaign related files. The files will be used reviewing and approving campaigns and track their progress. The storage should support file versioning and file replacing should be happening only with uploading a new version.

**Prerequisite**
Rancher cluster is installed - see issue #1 

**Describe alternatives you've considered**
See discussion here: https://github.com/podkrepi-bg/frontend/discussions/268

**Comment by imilchev** [comment]
done
